sbatch batch_run_minMAPE-0.sh
sleep 0.5
sbatch batch_run_minMAPE-1.sh
sleep 0.5
sbatch batch_run_minMAPE-2.sh
sleep 0.5
sbatch batch_run_minMAPE-3.sh
sleep 0.5
sbatch batch_run_minMAPE-4.sh
sleep 0.5
sbatch batch_run_minMAPE-5.sh
sleep 0.5
sbatch batch_run_minMAPE-6.sh
sleep 0.5
sbatch batch_run_minMAPE-7.sh
sleep 0.5
sbatch batch_run_minMAPE-8.sh
sleep 0.5
sbatch batch_run_minMAPE-9.sh
sleep 0.5
sbatch batch_run_minMAPE-10.sh
sleep 0.5
sbatch batch_run_minMAPE-11.sh
